### ISSUE TITLE
Scrape Data from the given Lists of Sources

### ISSUE THREAD

**Issue by marfox** [Wikidata/StrepHit#13]
Ordered by priority, i.e., amount of biographies, given in round brackets.
Specific numbers represent the amount *claimed* by the source.

# Web, unstructured
- [x] http://www.nndb.com/ ("Over 40k")
- [x] http://gameo.org/index.php?title=Welcome_to_GAMEO (15,900)
- [x] https://www.daao.org.au/ (15,783)
- [x] http://adb.anu.edu.au/ (15,320)
- [x] https://collection.cooperhewitt.org/people/ (12,744)
- [x] http://www.metal-archives.com/ (plenty)
- [x] http://www.bbc.co.uk/arts/yourpaintings/artists ("thousands")
- [x] http://munksroll.rcplondon.ac.uk/Biography/Search (6,950)
- [x] http://yba.llgc.org.uk/en/index.html (5k)
- [x] https://royalsociety.org/fellows/fellows-directory/ (1,596)
- [x] http://www.newulsterbiography.co.uk/index.php/home/browse (2,060)
- [x] https://dictionaryofarthistorians.org/a.html (few)
- [x] http://www.museothyssen.org/en/thyssen/artistas (few)
- [ ] http://plato.stanford.edu/index.html (few)
- [x] https://www.brown.edu/Administration/News_Bureau/Databases/Encyclopedia/ (few)
- [x] http://www.wga.hu/frames-e.html?/html/ (few)

# Web, semi-structured
- [x] http://www.genealogics.org/index.php (668,261)
- [x] https://rkd.nl/en/explore/artists (358,425)
- [x] http://www.catholic-hierarchy.org/bishop/laa.html (36,635)
- [x] http://www.uni-stuttgart.de/hi/gnt/dsi2/index.php?function=search&table_name=dsi (10,679)
- [x] http://structurae.net/persons/ (7,920)
- [x] http://cesar.org.uk/cesar2/people/index.php (7,505)
- [x] http://www.academia-net.org/ (2,271)
- [x] http://www.parliament.uk/mps-lords-and-offices/mps/ (650)
- [x] http://sculpture.gla.ac.uk/browse/index.php (few)
- [ ] https://www.itsanhonour.gov.au/index.cfm (**?**)
- [ ] https://www.getty.edu/research/tools/vocabularies/cona/ (**?**)

# Web, structured (RDF)
- [ ] http://vocab.getty.edu/ (**query needed**)
- [x] http://collection.britishmuseum.org/ (**query needed**)

# Wikisource
- [x] https://en.wikisource.org/wiki/Wikisource:WikiProject_Biographical_dictionaries/The_Biographical_Dictionary_of_America (plenty, use links to archive.org)
- [x] https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1885-1900 ("more than 29,000")
- [x] https://en.wikisource.org/wiki/Dictionary_of_Greek_and_Roman_Biography_and_Mythology (thousands)
- [x] https://en.wikisource.org/wiki/A_Naval_Biographical_Dictionary (thousands)
- [x] https://archive.org/stream/whowaswhocompani01londuoft/whowaswhocompani01londuoft_djvu.txt (thousands)
- [x] https://en.wikisource.org/wiki/A_Short_Biographical_Dictionary_of_English_Literature (few)
- [x] https://en.wikisource.org/wiki/Appletons%27_Cyclop%C3%A6dia_of_American_Biography (few)
- [x] https://en.wikisource.org/wiki/Catholic_Encyclopedia_%281913%29 (few)
- [x] https://en.wikisource.org/wiki/American_Medical_Biographies (few)
- [x] https://en.wikisource.org/wiki/A_Biographical_Dictionary_of_Ancient,_Medieval,_and_Modern_Freethinkers (few)
- [x] https://en.wikisource.org/wiki/The_Dictionary_of_Australasian_Biography (few)
- [x] https://en.wikisource.org/wiki/Dictionary_of_Christian_Biography_and_Literature_to_the_End_of_the_Sixth_Century (few)
- [x] https://en.wikisource.org/wiki/The_Indian_Biographical_Dictionary_(1915) (few)
- [x] https://en.wikisource.org/wiki/Men-at-the-Bar (few)
- [x] https://en.wikisource.org/wiki/A_Chinese_Biographical_Dictionary (few)
- [x] https://en.wikisource.org/wiki/Chronicle_of_the_law_officers_of_Ireland (few)
- [x] https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1901_supplement (few)
- [x] https://en.wikisource.org/wiki/Dictionary_of_National_Biography,_1912_supplement (few)
- [x] https://en.wikisource.org/wiki/A_Dictionary_of_Artists_of_the_English_School (very few)
- [x] https://en.wikisource.org/wiki/Modern_English_Biography (very few)
- [x] https://en.wikisource.org/wiki/A_Dictionary_of_Music_and_Musicians (very few)
- [x] https://en.wikisource.org/wiki/Who%27s_Who_in_China_(3rd_edition) (very few)
- [x] https://en.wikisource.org/wiki/Woman%27s_Who%27s_Who_of_America,_1914-15 (very few)
- [x] https://en.wikisource.org/wiki/Cartoon_portraits_and_biographical_sketches_of_men_of_the_day (very few)
- [x] https://en.wikisource.org/wiki/Men_of_the_Time,_eleventh_edition (very few)

**Comment by e-dorigatti** [comment]
Total number of scraped items: ca. 700k
Number of items with a non-empty biography: ca. 180k

![figure_1](https://cloud.githubusercontent.com/assets/5585926/13118344/1c68c220-d5a4-11e5-8dbc-113e015f0e4a.png)
