### ISSUE TITLE
Query ULAN for additional data

### ISSUE THREAD

**Issue by marfox** [Wikidata/StrepHit#16]
As kindly suggested by [Spinster](https://meta.wikimedia.org/wiki/User:Spinster) in [this discussion page](https://meta.wikimedia.org/wiki/Grants_talk:IEG/StrepHit:_Wikidata_Statements_Validation_via_References/Timeline).

**Comment by e-dorigatti** [comment]
Relevant commit: https://github.com/Wikidata/StrepHit/commit/7c672cbc21292a7fd68438ad3d5aadfa318851bd
Scraped 199502 items
