### ISSUE TITLE
Web Scraping Framework

### ISSUE THREAD

**Issue by marfox** [Wikidata/StrepHit#2]
Provide a table of candidate frameworks for Web scraping, with pros and cons details.

**Comment by e-dorigatti** [comment]
**Scrapy** http://scrapy.org/
 - Pros:
  - Full-fledged, feature-rich framework
  - Built-in scraped items saving
  - RFC2616 compliant HTTP cache, supporting fs/leveldb backend
  - Command line interface (good for debugging)
  - Very modular
 - Cons:
  - Could be overkill

**Grab** https://github.com/lorien/grab
 - Pros:
  - Simpler than scrapy
  - Supports redis/mongodb/mysql/postgres as alternative cache/queue backends
 - Cons:
  - No support for item saving (!!)

Useful analogy: scrapy ~ django, grab ~ flask

I'd go for scrapy
