### ISSUE TITLE
Use the POS-tagged corpus everywhere

### ISSUE THREAD

**Issue by e-dorigatti** [Wikidata/StrepHit#23]
For example, the verb ranking module [does](https://github.com/Wikidata/StrepHit/blob/master/strephit/corpus_analysis/rank_verbs.py#L150), while the [sentence extraction module](https://github.com/Wikidata/StrepHit/blob/master/strephit/extraction/extract_sentences.py) does not

**Comment by marfox** [comment]
this may be actually harmful when rebuilding the original sentence, as we may lose characters discarded at tokenization time
